// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB56UY0oHEEni6OM6sfnWqCxhazfeR6JEE',
    appId: '1:282836647176:web:431c66c994de0d680780bd',
    messagingSenderId: '282836647176',
    projectId: 'groceries-617e6',
    authDomain: 'groceries-617e6.firebaseapp.com',
    storageBucket: 'groceries-617e6.appspot.com',
    measurementId: 'G-5854XMYF92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8qT5VFdbvzwtmVAXnmvzPIQ4afrR1HA',
    appId: '1:282836647176:android:8c0ce0bb3e751b5b0780bd',
    messagingSenderId: '282836647176',
    projectId: 'groceries-617e6',
    storageBucket: 'groceries-617e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN_qyJZddw_Wz9EMJqfUgZI3HhaogqmaQ',
    appId: '1:282836647176:ios:8c1aac7b02d3c63f0780bd',
    messagingSenderId: '282836647176',
    projectId: 'groceries-617e6',
    storageBucket: 'groceries-617e6.appspot.com',
    androidClientId: '282836647176-qov3m6hb69s7jh3fqf69slh5lnmhn0e8.apps.googleusercontent.com',
    iosClientId: '282836647176-bav0ovie6qmepbv4mmlbdhjdo3al1q4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceries',
  );
}
